name: 01b Hola mundo
on:
  workflow_dispatch:
  push:
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Hola Francisco
      run: echo "Hello Francisco!!"
